// DO NOT EDIT — generated by scripts/generate_webui_types.py from the
// FastAPI app's OpenAPI schema.  Run that script (or `npm run gen:types`)
// after changing a native `/saklas/v1/*` response shape; CI regenerates and
// fails on a diff.
//
// These are the REST response shapes only.  Request bodies, the WebSocket
// frame vocabulary, and the dashboard's own client-local types are
// hand-written in `./types`, which re-exports everything below — import from
// `./types`, never from here.

import type {
  LoomTokenRowJSON,
  ManifoldDomain,
  ManifoldPcaDiagnostics,
  ManifoldSpectralDiagnostics,
} from "./types";

/** Active path: chat messages + a parallel node-id list. */
export interface ActivePathJSON {
  active_node_id: string;
  rev: number;
  messages: ChatMessageJSON[];
  node_ids: string[];
}

/** ``CastMember.to_dict()`` plus the server-derived ``origin``. */
export interface CastMemberJSON {
  recipe: RecipeJSON | null;
  notes: string;
  origin?: string;
}

export interface CastMemberResponse {
  label: string;
  member: CastMemberJSON;
}

export interface CastRosterResponse {
  cast: Record<string, CastMemberJSON>;
}

export interface ChatMessageJSON {
  role: "user" | "assistant" | "system";
  content: string;
}

/** One candidate's score within a context's restricted-choice set. */
export interface ChoiceScore {
  text: string;
  label: string;
  n_tokens: number;
  sum_logprob: number;
  mean_logprob: number;
  prob_sum: number;
  prob_mean: number;
}

export interface ChoiceScores {
  steering: string | null;
  choices: ChoiceScore[];
}

export interface CorrelationData {
  names: string[];
  matrix: Record<string, Record<string, number | null>>;
  layers_shared: Record<string, number>;
}

/**
 * Wire form of ``instruments.types.DepthSummary``.
 *
 * ``basis`` travels with the numbers because ``center`` means three
 * mathematically unrelated things across the families.
 */
export interface DepthSummaryJSON {
  center: number[];
  spread: number[];
  basis: string;
}

export interface DiffReadingDeltaJSON {
  name: string;
  delta: number;
  a_value: number;
  b_value: number;
}

export interface DiffTextSpanJSON {
  state: string;
  text: string;
}

export interface DiffTokenSpanJSON {
  a_index: number;
  b_index: number;
  a_text: string;
  b_text: string;
  aligned: boolean;
  reading_deltas: DiffReadingDeltaJSON[];
}

/** ``GET .../tree/edge-label`` — empty string when the recipes match. */
export interface EdgeLabelResponse {
  label: string;
}

/** ``POST .../extract`` — the JSON (non-SSE) branch. */
export interface ExtractResponse {
  done: boolean;
  profile: VectorInfo;
  canonical: string;
  progress?: string[];
}

export interface FilterMatchesJSON {
  expr: string;
  matching_node_ids: string[];
}

export interface GeometryInstrumentJSON {
  readings: Record<string, ProbeReadingJSON>;
  binding?: MeasurementBindingJSON;
}

/** Geometry live state — an all-or-nothing per-token scoring switch. */
export interface GeometryLiveState {
  enabled: boolean;
}

/** One attached geometry (Monitor subspace) probe, any rank. */
export interface GeometryProbeInfo {
  family: "geometry";
  name: string;
  manifold: string;
  top_n: number;
  layers: number[];
  node_labels: string[];
  node_count: number;
  domain: ManifoldDomain | Record<string, never>;
  intrinsic_dim: number;
  feature_space: string;
  is_affine: boolean;
  node_coords: number[][] | null;
}

/** What a read family supports, declared by the server rather than guessed. */
export interface InstrumentCapabilities {
  sources: boolean;
  preparations: string[];
  token_readout: boolean;
  source_switch: boolean;
}

/**
 * One read family's state.
 *
 * The SAME block is listed by ``GET .../instruments`` and embedded in
 * ``session_info.instruments`` — one representation of instrument state.
 */
export interface InstrumentFamilyBlock {
  family: string;
  live: SaeLiveState | LensLiveState | GeometryLiveState;
  source: string | null;
  probes: string[];
  capabilities: InstrumentCapabilities;
}

/** One usable artifact source (lens binding / SAE source row). */
export interface InstrumentSourceJSON {
  source: string;
  kind?: string;
  name?: string;
  active?: boolean;
  provider?: string;
  repo_id?: string;
  repo_revision?: string;
  checkpoint?: string;
  layer?: number;
  features?: number;
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface InstrumentsResponse {
  instruments: InstrumentFamilyBlock[];
}

export interface JointLogprobRowJSON {
  a_index: number;
  b_index: number;
  a_text: string;
  b_text: string;
  aligned: boolean;
  lp_a_in_a: number | null;
  lp_b_in_b: number | null;
  lp_a_in_b: number | null;
  lp_b_in_a: number | null;
  rank_changed: boolean;
  approx_kl: number | null;
}

export interface JointLogprobsJSON {
  a_id: string;
  b_id: string;
  parent_id: string | null;
  rows: JointLogprobRowJSON[];
  n_rank1_changed: number;
}

export interface LensAggregateTokenJSON {
  token: string;
  strength: number;
  com: number;
  spread: number;
}

export interface LensInstrumentJSON {
  binding: MeasurementBindingJSON;
  readings?: Record<string, ScalarReadingJSON>;
  readout?: LensReadoutBlockJSON;
}

/** Lens live state — the resolved fitted-layer set. */
export interface LensLiveState {
  enabled: boolean;
  layers: number[] | null;
}

/** One pinned J-lens token probe (the readout channel). */
export interface LensProbeInfo {
  family: "lens";
  name: string;
  layers: number[];
  intrinsic_dim: number;
  feature_space: string;
  word: string;
  token_id: number | null;
}

export interface LensReadoutBlockJSON {
  layers: LensReadoutLayerJSON[];
  aggregate: LensAggregateTokenJSON[];
}

export interface LensReadoutLayerJSON {
  layer: number;
  tokens: LensReadoutTokenJSON[];
}

export interface LensReadoutTokenJSON {
  token: string;
  id: number;
  logprob: number;
}

export interface LensTokenValidationJSON {
  word: string;
  token_id: number;
}

/** A single node plus its ordered child ids (the mutation responses). */
export interface LoomNodeDetailJSON {
  id: string;
  parent_id: string | null;
  role: "user" | "assistant" | "system";
  text: string;
  role_label: string | null;
  thinking_text: string | null;
  aggregate_readings: Record<string, number>;
  applied_steering: string | null;
  finish_reason: string | null;
  starred: boolean;
  notes: string;
  created_at: number;
  edited_at: number | null;
  edit_count: number;
  mean_logprob: number | null;
  mean_surprise: number | null;
  recipe: RecipeJSON | null;
  tokens: LoomTokenRowJSON[] | null;
  thinking_tokens: LoomTokenRowJSON[] | null;
  raw_token_ids: number[] | null;
  children: string[];
}

/**
 * ``LoomNode.to_dict(include_tokens=True)``.
 *
 * ``tokens`` / ``thinking_tokens`` stay opaque here: a token row is an
 * open, feature-dependent capture record (the ``measurements`` envelope,
 * logit alternatives, per-layer heatmap channels), and running thousands
 * of them through response validation on every tree fetch would be both
 * slow and a rejection risk for restored trees.  The generator maps them
 * onto the hand-written ``LoomTokenRowJSON``.
 */
export interface LoomNodeJSON {
  id: string;
  parent_id: string | null;
  role: "user" | "assistant" | "system";
  text: string;
  role_label: string | null;
  thinking_text: string | null;
  aggregate_readings: Record<string, number>;
  applied_steering: string | null;
  finish_reason: string | null;
  starred: boolean;
  notes: string;
  created_at: number;
  edited_at: number | null;
  edit_count: number;
  mean_logprob: number | null;
  mean_surprise: number | null;
  recipe: RecipeJSON | null;
  tokens: LoomTokenRowJSON[] | null;
  thinking_tokens: LoomTokenRowJSON[] | null;
  raw_token_ids: number[] | null;
}

/** ``LoomTree.to_dict(include_tokens=True)`` + the effective cast roster. */
export interface LoomTreeJSON {
  tree_format: number;
  saklas_version: string;
  model_id: string | null;
  session_id: string | null;
  name: string | null;
  rev: number;
  root_id: string;
  active_node_id: string;
  nodes: LoomNodeJSON[];
  children_of: Record<string, string[]>;
  cast: Record<string, CastMemberJSON>;
}

export interface ManifoldDeleteResponse {
  namespace: string;
  name: string;
  source: string;
  removed: boolean;
  rematerializes_on_restart: boolean;
}

/** Per-fitted-tensor record in the manifold detail shape. */
export interface ManifoldFitInfo {
  stem: string;
  method: string;
  feature_space: string;
  node_count: number;
  nodes_sha256: string | null;
  fit_mode: string;
  hyperparams?: Record<string, number | string>;
  diagnostics?: ManifoldPcaDiagnostics | ManifoldSpectralDiagnostics;
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

/**
 * ``_manifold_json`` — ``manifold_summary`` plus the session-aware extras.
 *
 * ``nodes`` / ``fitted`` are detail-only (``full=True``); ``advisories``
 * rides the authoring response; ``done`` / ``layers_fitted`` /
 * ``feature_space`` ride the generate + fit JSON branches.
 */
export interface ManifoldInfo {
  namespace: string;
  name: string;
  description: string;
  source: string;
  tags: string[];
  template_ref: string | null;
  fit_mode: string;
  is_discover: boolean;
  domain: ManifoldDomain;
  domain_label: string;
  intrinsic_dim: number;
  min_nodes: number | null;
  node_count: number;
  node_labels: string[];
  node_coords: number[][];
  node_roles: (string | null)[];
  node_kinds: (string | null)[];
  hyperparams: Record<string, number | string>;
  fitted_models: string[];
  tensor_variants: Record<string, string[]>;
  fitted_for_session: boolean;
  stale: boolean;
  resolved_fit_mode: string | null;
  nodes?: ManifoldNodeDetail[];
  fitted?: ManifoldFitInfo[];
  advisories?: string[];
  done?: boolean;
  layers_fitted?: number;
  feature_space?: string;
  progress?: string[];
}

export interface ManifoldListResponse {
  manifolds: ManifoldInfo[];
}

/**
 * One node in the detail (``full=True``) manifold shape.
 *
 * ``coords`` is the authored layout for an authored folder, the derived
 * per-model layout for a fitted discover folder, and ``null`` for a
 * discover folder with no fit for the loaded model.
 */
export interface ManifoldNodeDetail {
  label: string;
  coords: number[] | null;
  statements: string[];
  role: string | null;
}

export interface ManifoldSearchResponse {
  query: string;
  results: RemoteManifoldInfo[];
}

/** What a family was measuring: source identity + recipe steering. */
export interface MeasurementBindingJSON {
  source: string | null;
  steering: string | null;
  layer?: number | null;
}

export interface MeasurementInstrumentsJSON {
  geometry?: GeometryInstrumentJSON;
  lens?: LensInstrumentJSON;
  sae?: SaeInstrumentJSON;
}

/** The one versioned read-side wire record. */
export interface MeasurementsEnvelopeJSON {
  version: number;
  scope: "token" | "aggregate" | "replay";
  provenance: "captured" | "replayed";
  instruments: MeasurementInstrumentsJSON;
  scores?: Record<string, number>;
  per_layer_scores?: Record<string, Record<string, number>>;
}

/** The replay endpoints' response body. */
export interface MeasurementsReplayJSON {
  measurements: MeasurementsEnvelopeJSON | null;
}

export interface NodeDiffJSON {
  a_id: string;
  b_id: string;
  parent_id: string | null;
  a_text: string;
  b_text: string;
  a_applied_steering: string | null;
  b_applied_steering: string | null;
  parent_applied_steering: string | null;
  steering_delta: string;
  parent_to_a_delta: string;
  parent_to_b_delta: string;
  text: DiffTextSpanJSON[];
  readings: DiffReadingDeltaJSON[];
  per_token: DiffTokenSpanJSON[];
}

/** Cross-layer whitened cosine matrix between two named profiles/probes. */
export interface PairwiseCompareResponse {
  a: string;
  b: string;
  metric: string;
  layers_a: number[];
  layers_b: number[];
  matrix: ((number | null)[])[];
  model: string | null;
}

export interface PreparationProgress {
  current: number | null;
  total: number | null;
  unit: string;
}

/** One shape over lens ``fetch``/``fit`` and sae ``fetch``/``train``. */
export interface PreparationStatusJSON {
  state: string;
  operation: string | null;
  progress: PreparationProgress | null;
  message: string | null;
  error: string | null;
  started_at: number | null;
  finished_at: number | null;
  cancellable: boolean;
  live_layers?: number[] | null;
  source?: string | null;
  release?: string | null;
  name?: string | null;
  info?: SaeRuntimeInfo | null;
}

/** ``GET .../probes/defaults`` — ``{tag: [manifold name]}``. */
export interface ProbeDefaultsResponse {
  defaults: Record<string, string[]>;
}

export interface ProbeGeometryResponse {
  name: string;
  manifold: string;
  intrinsic_dim: number;
  is_affine: boolean;
  node_labels: string[];
  rank_uniform: boolean;
  layers: Record<string, ProbeLayerGeometry>;
}

/** One fitted layer's geometry for the probe-inspector plot. */
export interface ProbeLayerGeometry {
  layer: number;
  rank: number;
  intrinsic_dim: number;
  is_affine: boolean;
  node_white: number[][];
  neutral_white: number[];
  pca_rotation: number[][] | null;
  explained_variance_pcs: number[] | null;
  mahalanobis_share: number;
  overlay: ProbeOverlay | null;
}

export interface ProbeListResponse {
  probes: (GeometryProbeInfo | LensProbeInfo | SaeProbeInfo)[];
}

/** A curved fit's curve/surface overlay, sampled into the whitened frame. */
export interface ProbeOverlay {
  kind: string;
  points: number[][];
  grid_shape?: number[];
}

/**
 * Wire form of ``ProbeReading.to_dict()`` — the geometry reading.
 *
 * The complete key set that serializer emits, in its order.  Declaring it
 * here (rather than as an anonymous ``dict[str, Any]`` on the channel)
 * is what lets the generated dashboard types name the geometry reading
 * instead of falling back to an opaque record.
 */
export interface ProbeReadingJSON {
  fraction: number;
  nearest: [string, number][];
  coords: number[];
  residual: number;
  fraction_per_layer: Record<string, number>;
  coords_per_layer: Record<string, number[]>;
  residual_per_layer: Record<string, number>;
  assignment?: [string, number][];
  membership?: number;
  depth_com?: number[];
  depth_spread?: number[];
  subspace_coords_per_layer?: Record<string, number[]>;
}

export interface ProfileListResponse {
  profiles: VectorInfo[];
}

/** ``Recipe.to_dict()`` — the per-node reproducibility receipt. */
export interface RecipeJSON {
  steering: string | null;
  sampling: RecipeSamplingJSON | null;
  thinking: boolean | null;
  seed: number | null;
  probes: string[];
  probe_hashes: Record<string, string>;
}

/**
 * A stamped recipe's sampling block.
 *
 * ``Recipe.to_dict`` walks ``fields(SamplingConfig)``, so every field is
 * present — the two container fields are normalized on the way out
 * (``stop`` to a list, ``logit_bias`` to string-keyed floats).
 */
export interface RecipeSamplingJSON {
  temperature: number | null;
  top_p: number | null;
  top_k: number | null;
  max_tokens: number | null;
  seed: number | null;
  stop: string[] | null;
  logit_bias: Record<string, number> | null;
  presence_penalty: number;
  frequency_penalty: number;
  logprobs: number | null;
  return_hidden: boolean;
  return_top_k: number;
  user_role: string | null;
  assistant_role: string | null;
  persist_per_layer_scores: boolean;
  persist_subspace_coords: boolean;
  return_probe_readings: boolean;
}

/** One Hugging Face search row, as the picker renders it. */
export interface RemoteManifoldInfo {
  name: string;
  namespace: string;
  description: string;
  tags: string[];
  node_count: number;
  domain_label: string;
  fit_mode: string;
  tensor_models: string[];
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface SaeFeatureJSON {
  id: number;
  activation: number;
  label: string | null;
  max_act: number | null;
}

export interface SaeFeatureMetaEntry {
  label: string | null;
  max_act: number | null;
}

/** ``POST .../instruments/sae/features/metadata`` — the discovery backfill. */
export interface SaeFeatureMetaResponse {
  features: Record<string, SaeFeatureMetaEntry>;
}

/**
 * ``POST .../instruments/sae/features/validate`` — a read-only range +
 * metadata check against the resident SAE.
 */
export interface SaeFeatureValidationJSON {
  id: number;
  label: string | null;
  layer: number;
  max_act: number | null;
}

export interface SaeInstrumentJSON {
  binding: MeasurementBindingJSON;
  readings?: Record<string, ScalarReadingJSON>;
  readout?: SaeReadoutBlockJSON;
}

/** SAE live state — the resident layer + source. */
export interface SaeLiveState {
  enabled: boolean;
  layer: number | null;
  source: string | null;
}

/** One pinned resident SAE feature probe (the encoder readout channel). */
export interface SaeProbeInfo {
  family: "sae";
  name: string;
  layers: number[];
  intrinsic_dim: number;
  feature_space: string;
  feature_id: number;
  label: string | null;
  max_act: number | null;
}

export interface SaeReadoutBlockJSON {
  features: SaeFeatureJSON[];
}

/**
 * One provider release candidate from the SAELens registry.
 *
 * Distinct from :class:`InstrumentSourceJSON`: a release is a *candidate*
 * the dashboard can still fetch, keyed by ``release`` rather than by the
 * ``source`` string a prepared row is addressed with.
 */
export interface SaeReleaseJSON {
  release: string;
  model: string | null;
  layers: number[];
  repo_id: string | null;
  neuronpedia: boolean;
  source: "local" | "saelens";
}

/** Resident SAE identity once a fetch/train preparation lands. */
export interface SaeRuntimeInfo {
  release?: string;
  revision?: string | null;
  fingerprint?: string | null;
  layer?: number;
  width?: number;
  sae_id?: string | null;
  repo_id?: string | null;
  neuronpedia_id?: string | null;
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

/** ``session_info.config`` — the session's default sampling knobs. */
export interface SamplingFields {
  temperature: number | null;
  top_p: number | null;
  top_k: number | null;
  max_tokens: number | null;
  system_prompt: string | null;
  thinking: boolean | null;
}

/**
 * Wire form of ``ScalarReading.to_dict()`` — the lens/SAE reading.
 *
 * One value with an explicit ``unit``, its per-layer trace, and a depth
 * summary.  No geometry fields: a readout channel has no subspace behind
 * it.  ``meta`` is emitted only when the producer attached one.
 */
export interface ScalarReadingJSON {
  value: number;
  unit: string;
  per_layer: Record<string, number>;
  depth: DepthSummaryJSON | null;
  meta?: Record<string, unknown>;
}

export interface ScoreTemplateResponse {
  template: string;
  namespace: string;
  steering: string | null;
  contexts: ChoiceScores[];
}

/** ``session_info()`` — the single session's full descriptor. */
export interface SessionInfo {
  id: string;
  model_id: string;
  device: string;
  dtype: string;
  created: number;
  config: SamplingFields;
  profiles: string[];
  probes: string[];
  history_length: number;
  supports_thinking: boolean;
  thinking_is_optional: boolean;
  is_base_model: boolean;
  jlens_fitted: boolean;
  instruments: InstrumentFamilyBlock[];
  default_steering: string | null;
  role_substitution_supported: boolean;
  user_role_supported: boolean;
  default_assistant_role: string | null;
  default_user_role: string | null;
  scene_mode: boolean;
  thinking_input_supported: boolean;
  strips_history_thinking: boolean;
}

export interface SessionListResponse {
  sessions: SessionInfo[];
}

export interface SourceSwitchResponse {
  source: string;
  live_layers: number[];
}

export interface SourcesResponse {
  sources: InstrumentSourceJSON[];
  releases?: SaeReleaseJSON[];
}

/** ``POST .../steering/validate`` — a form result, not a failed request. */
export interface SteeringValidationResponse {
  valid: boolean;
  expression: string;
  error: string | null;
}

export interface TemplateContextJSON {
  turns: TemplateTurnJSON[];
  assistant: string;
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface TemplateDeleteResponse {
  namespace: string;
  name: string;
  removed: boolean;
}

/** A template summary plus the full contexts. */
export interface TemplateDetail {
  namespace: string;
  name: string;
  slot: string;
  n_values: number;
  n_contexts: number;
  values: string[];
  labels: string[];
  description: string;
  tags: string[];
  contexts: TemplateContextJSON[];
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface TemplateListResponse {
  templates: TemplateSummary[];
}

/** A template list row. */
export interface TemplateSummary {
  namespace: string;
  name: string;
  slot: string;
  n_values: number;
  n_contexts: number;
  values: string[];
  labels: string[];
  description: string;
  tags: string[];
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface TemplateTurnJSON {
  role: string;
  content: string;
  /** Open shape — the producer may carry more than the
   *  contract names; unknown keys ride through. */
  [key: string]: unknown;
}

export interface TranscriptLoadResponseJSON {
  leaf_id: string;
  rev: number;
  guards: string[];
}

export interface TranscriptResponse {
  yaml: string;
  node_id: string;
}

export interface TreeBranchResponse {
  node_id: string;
  node: LoomNodeDetailJSON;
  active_path: ActivePathJSON;
}

export interface TreeDeleteResponse {
  removed: number;
}

export interface TreeRestoreResponse {
  rev: number;
  root_id: string;
  active_node_id: string;
  nodes: number;
}

/** ``profile_to_json`` — a registered steering profile's identity. */
export interface VectorInfo {
  name: string;
  layers: number[];
  metadata: Record<string, unknown>;
}
