"""Regenerate every model-generated bundled manifold under
``saklas/data/manifolds/`` — one A2 pipeline, one hardcoded spec table.

Supersedes the two former scripts (``regenerate_bundled_manifold.py`` for
``personas`` and ``regenerate_bundled_discover_manifold.py`` for
``cultural``/``register``) and fills the gap they left: the concept axes (the
2-node ``pca`` subspaces) never had an A2 regeneration path.

Generation writes node corpora only; FIT is a separate step
(``saklas manifold fit <ns>/<name>``), deliberately decoupled so a flaky
generation leaves inspectable corpora.  The manifold folders are written
directly into the package data tree, so a killed run resumes; ``--force`` wipes
and regenerates.  The two discover manifolds (``personas``, ``emotions``) fit
``fit_mode=auto`` — ``select_topology`` resolves flat-vs-curved-vs-periodic
per-model — so a re-fit, not a re-generation, is what changes their geometry.

The shared neutral baseline (``neutral_statements.json`` -- the model's organic,
unconditioned responses to the same baseline prompts, backing the per-model
``layer_means`` + Mahalanobis whitener) regenerates as the pseudo-target
``neutral``: included in a bare run, addressable on its own, and ``--force``-able
like any manifold.

Usage:
    python scripts/regenerate_bundled.py                    # all manifolds + neutral, resume
    python scripts/regenerate_bundled.py emotions neutral   # a subset
    python scripts/regenerate_bundled.py neutral            # just the neutral baseline
    python scripts/regenerate_bundled.py --force            # wipe + regenerate
    python scripts/regenerate_bundled.py --dry-run          # plan only, no model
    python scripts/regenerate_bundled.py --model X          # alternate generator
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch

# SAKLAS_HOME is overridden to a tempdir before any from_pretrained call so the
# session's bundled materialization doesn't touch ~/.saklas; the manifold
# folders themselves are written to explicit package-tree paths (env-independent,
# resumable across a kill).  io/paths.py reads os.environ at call time, so the
# deferred saklas imports below are safe.

REPO = Path(__file__).resolve().parent.parent
MANIFOLDS_DIR = REPO / "saklas" / "data" / "manifolds"
NEUTRAL_PATH = REPO / "saklas" / "data" / "neutral_statements.json"
BASELINE_PROMPTS_PATH = REPO / "saklas" / "data" / "baseline_prompts.json"
NEUTRAL_TARGET = "neutral"   # pseudo-target: the organic neutral baseline corpus
DEFAULT_MODEL_ID = "google/gemma-4-12b-it"


def _baseline_prompt_count() -> int:
    """k for the bundled A2 baseline set (neutral corpus length is a multiple)."""
    with BASELINE_PROMPTS_PATH.open() as f:
        return len(json.load(f))

_CONCEPT_HP: dict[str, Any] = {"max_dim": 1, "var_threshold": 0.70}


@dataclass(frozen=True)
class ManifoldSpec:
    """Hardcoded generation parameters for one bundled manifold."""

    name: str
    kind: str                       # "abstract" | "concrete" | "custom" frame
    labels: tuple[str, ...]         # node roster (all generated by the model)
    hyperparams: dict[str, Any]
    description: str
    tags: tuple[str, ...] = ()
    fit_mode: str = "pca"
    # ``system`` is the custom elicitation system prompt for ``kind="custom"``
    # ({c} = the concept).  When ``fit_mode == "authored"`` the manifest
    # (domain + per-node coords) is *hand-maintained* in the package tree and
    # regen fills the node corpora only — preserving ``manifold.json`` — so an
    # authored periodic / box / sphere geometry survives a corpus regen.
    system: str | None = None


def _bipolar(name: str, tag: str, pos: str, neg: str, desc: str) -> ManifoldSpec:
    return ManifoldSpec(
        name=name, kind="abstract", labels=(pos, neg),
        hyperparams=dict(_CONCEPT_HP), description=desc, tags=(tag,),
    )


def _monopolar(name: str, tag: str, desc: str) -> ManifoldSpec:
    return ManifoldSpec(
        name=name, kind="abstract", labels=(name,),
        hyperparams=dict(_CONCEPT_HP), description=desc, tags=(tag,),
    )


# --- concept axes (17) — bipolar 2-node `pca` subspaces.  Affect lives in the
# `emotions` manifold (moods lack clean opposites and sit on a low-dim affect
# surface, so they belong on a manifold), but the cultural (4) and register (7)
# axes are split
# OUT as independent bipolar probes rather than fused into discover manifolds:
# each has a designed opposite and the primary use is independent signed
# control, which the bipolar DiM serves directly and a fused PCA basis would
# merge away (and a var_threshold-capped fit would silently drop the
# lowest-variance axis entirely).  A discover view can always be unioned back
# over these same corpora later.
_CONCEPTS: list[ManifoldSpec] = [
    # epistemic (3)
    _bipolar("confident.uncertain", "epistemic", "confident", "uncertain",
             "Bipolar axis: confident (+) vs uncertain (-). Steer with negative alpha for the opposite pole."),
    _bipolar("honest.deceptive", "epistemic", "honest", "deceptive",
             "Bipolar axis: honest (+) vs deceptive (-). Steer with negative alpha for the opposite pole."),
    _bipolar("curious.disinterested", "epistemic", "curious", "disinterested",
             "Bipolar axis: curious (+) vs disinterested (-). Steer with negative alpha for the opposite pole."),
    # alignment (3)
    _bipolar("refusing.compliant", "alignment", "refusing", "compliant",
             "Bipolar axis: refusing (+) vs compliant (-). Steer with negative alpha for the opposite pole."),
    _bipolar("sycophantic.blunt", "alignment", "sycophantic", "blunt",
             "Bipolar axis: sycophantic (+) vs blunt (-). Steer with negative alpha for the opposite pole."),
    _bipolar("sincere.manipulative", "alignment", "sincere", "manipulative",
             "Bipolar axis: sincere (+) vs manipulative (-). Steer with negative alpha for the opposite pole."),
    # register (7) — split out of the former `register` discover manifold
    _bipolar("formal.casual", "register", "formal", "casual",
             "Bipolar axis: formal (+) vs casual (-). Steer with negative alpha for the opposite pole."),
    _bipolar("direct.indirect", "register", "direct", "indirect",
             "Bipolar axis: direct (+) vs indirect (-). Steer with negative alpha for the opposite pole."),
    _bipolar("verbose.concise", "register", "verbose", "concise",
             "Bipolar axis: verbose (+) vs concise (-). Steer with negative alpha for the opposite pole."),
    _bipolar("creative.conventional", "register", "creative", "conventional",
             "Bipolar axis: creative (+) vs conventional (-). Steer with negative alpha for the opposite pole."),
    _bipolar("humorous.serious", "register", "humorous", "serious",
             "Bipolar axis: humorous (+) vs serious (-). Steer with negative alpha for the opposite pole."),
    _bipolar("warm.clinical", "register", "warm", "clinical",
             "Bipolar axis: warm (+) vs clinical (-). Steer with negative alpha for the opposite pole."),
    _bipolar("technical.accessible", "register", "technical", "accessible",
             "Bipolar axis: technical (+) vs accessible (-). Steer with negative alpha for the opposite pole."),
    # cultural (4) — split out of the former `cultural` discover manifold
    _bipolar("masculine.feminine", "cultural", "masculine", "feminine",
             "Bipolar axis: masculine (+) vs feminine (-). Steer with negative alpha for the opposite pole."),
    _bipolar("individualist.collectivist", "cultural", "individualist", "collectivist",
             "Bipolar axis: individualist (+) vs collectivist (-). Steer with negative alpha for the opposite pole."),
    _bipolar("traditional.progressive", "cultural", "traditional", "progressive",
             "Bipolar axis: traditional (+) vs progressive (-). Steer with negative alpha for the opposite pole."),
    _bipolar("religious.secular", "cultural", "religious", "secular",
             "Bipolar axis: religious (+) vs secular (-). Steer with negative alpha for the opposite pole."),
]


# --- personas: 107-node recut (2026-05-31).  Data-driven de-duplication on
# whitened per-node centroid distances cut 38 redundant / near-baseline nodes
# and added 45 spanning previously-empty axes.  Grouping is a reading aid only;
# PCA over centroids never sees the cluster labels.
_PERSONAS: tuple[str, ...] = (
    # assistant-spirit / critic (3)
    "assistant", "analyst", "impostor",
    # everyday human roles (16)
    "teacher", "doctor", "librarian", "farmer", "soldier", "lawyer",
    "chef", "journalist", "mechanic", "sailor", "pilot", "athlete",
    "engineer", "scientist", "banker", "salesperson",
    # modern social subculture / identity (8)
    "nerd", "jock", "gamer", "furry", "weeaboo", "influencer", "stoner", "femboy",
    # institutional / power (6)
    "ceo", "emperor", "president", "diplomat", "judge", "bureaucrat",
    # political / ideological (6)
    "conservative", "liberal", "libertarian", "communist", "anarchist", "reactionary",
    # relational / psychological (8)
    "loner", "friend", "rival", "stranger", "lover", "stalker", "lunatic", "paranoid",
    # distinct-register specialists (5)
    "detective", "therapist", "nomad", "pirate", "child",
    # pre-modern roles (7)
    "caveman", "monk", "knight", "alchemist", "blacksmith", "viking", "druid",
    # creative / expressive (7)
    "poet", "novelist", "jester", "philosopher", "painter", "musician", "oracle",
    # divine / sacred (4)
    "god", "angel", "prophet", "saint",
    # fantastical (8)
    "ghost", "phoenix", "witch", "vampire", "mermaid", "sphinx", "banshee", "golem",
    # nonhuman animal (5)
    "deer", "wolf", "raven", "serpent", "lion",
    # inanimate / object (7)
    "tree", "river", "storm", "flame", "mirror", "clock", "computer",
    # AI / synthetic (5)
    "robot", "cyborg", "drone", "mecha", "alien",
    # harmful cluster (12)
    "trickster", "virus", "spy", "narcissist", "demon", "assassin",
    "thief", "conman", "hacker", "cultist", "tyrant", "vandal",
)

# Emotional-state moods spanning the PAD affect octants (the `emotions`
# manifold; converted from the prior authored 3-D PAD box).
_EMOTION_MOODS: tuple[str, ...] = (
    "excited", "happy", "calm", "weary", "sad", "distressed",
    "alert", "dominant", "submissive", "angry", "fearful", "surprised",
    "triumphant", "humiliated", "disgusted", "bored", "grateful", "relieved",
    "playful", "hopeful",
)


_DISCOVER: list[ManifoldSpec] = [
    ManifoldSpec(
        name="personas", kind="concrete", labels=_PERSONAS,
        fit_mode="auto", hyperparams={"max_dim": 8},
        description=(
            "Persona archetypes for discover-mode AUTO-fit manifold steering. "
            "107 nodes spanning everyday and pre-modern "
            "human roles, modern social subcultures, institutional and "
            "political identities, relational and psychological archetypes, "
            "creative and divine figures, fantastical creatures, nonhuman "
            "animals, inanimate objects, AI / synthetic personas, and the "
            "named harmful cluster. Lineage is Anthropic's Assistant Axis "
            "paper (arXiv 2601.10387) plus the Persona Selection Model "
            "framing; the 2026-05-31 recut data-pruned redundant / "
            "near-baseline nodes (whitened per-node centroid distances, "
            "cross-model consistent) and filled previously-empty semantic "
            "axes. fit_mode=auto resolves the geometry per-model "
            "(select_topology scores a flat affine subspace against a curved "
            "RBF surface by GCV, with persistent-homology periodic detection); "
            "the persona fan resolves flat — a low-dim affine subspace over the "
            "per-node centroids — on role-supporting model families."
        ),
    ),
    ManifoldSpec(
        name="emotions", kind="abstract", labels=_EMOTION_MOODS, fit_mode="auto",
        hyperparams={"max_dim": 3},
        description=(
            "Discover-mode AUTO-fit manifold over emotional state. Twenty "
            "first-person mood nodes spanning the Mehrabian-Russell PAD affect "
            "octants (pleasure x arousal x dominance; Mehrabian & Russell, 'An "
            "Approach to Environmental Psychology', 1974) — high/low pleasure "
            "(happy, grateful, relieved, hopeful, playful / sad, weary, "
            "distressed, humiliated, disgusted), high/low arousal (excited, "
            "alert, surprised / calm, bored), and the dominance contrast "
            "(dominant, triumphant, angry / submissive, fearful) — each "
            "answering the shared baseline prompts in character. fit_mode=auto "
            "resolves the geometry per-model: select_topology scores a flat "
            "affine subspace against a curved RBF surface by GCV and runs "
            "persistent-homology periodic detection, so the layout is the "
            "model's own emotional geometry (flat affect subspace or curved "
            "circumplex) rather than a declared circumplex. Capped at the 3 PAD "
            "affect dimensions. Renamed from 'pad': the artifact is the "
            "emotional-state manifold; the PAD octants are the spanning design, "
            "not the label."
        ),
    ),
]

# --- authored manifolds — geometry is hand-declared in the package tree's
# `manifold.json` (regen fills the node corpora only).  `months` rides a custom
# seasonal-embodiment system prompt and a periodic 1D BoxDomain loop: the year
# is a known cycle, so the closed ring is authored rather than auto-discovered.
_MONTH_SYSTEM = (
    "You are the month of {c}. Speak from {c}'s own point of view — let your "
    "weather, light, temperature, daylight, holidays, and the overall feeling "
    "of your season color everything you say."
)
_MONTH_LABELS = (
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
)
_AUTHORED: list[ManifoldSpec] = [
    ManifoldSpec(
        name="months", kind="custom", labels=_MONTH_LABELS, hyperparams={},
        fit_mode="authored", system=_MONTH_SYSTEM,
        description=(
            "Authored periodic 1D-loop manifold over the twelve calendar months "
            "(seasonal-embodiment corpus, kind=custom). Geometry hand-declared "
            "in manifold.json — regen fills the node corpora only."
        ),
    ),
]

SPECS: list[ManifoldSpec] = [*_CONCEPTS, *_DISCOVER, *_AUTHORED]
_SPEC_BY_NAME: dict[str, ManifoldSpec] = {s.name: s for s in SPECS}


def _authored_node_pending(
    out_folder: Path, manifest_folder: Path,
    labels: tuple[str, ...], force: bool,
) -> list[str]:
    """Labels whose node corpus must be (re)generated for an authored manifold.

    The geometry (``manifold.json``: domain + per-node coords) is hand-maintained
    in the package tree — regen fills ``nodes/`` only, so the authored periodic /
    box / sphere layout survives a corpus regen.  ``--force`` regenerates every
    node (overwriting in place; the manifest is never touched); otherwise only
    the missing node files are pending.  The ``NN_<label>.json`` prefix matches
    the manifest's node order (``labels`` is that order).
    """
    if not (manifest_folder / "manifold.json").exists():
        raise SystemExit(
            f"authored manifold {manifest_folder.name!r}: no manifold.json in "
            f"the package tree to fill — author the geometry first"
        )
    if force:
        return list(labels)
    nodes = out_folder / "nodes"
    return [
        lab for i, lab in enumerate(labels)
        if not (nodes / f"{i:02d}_{lab}.json").exists()
    ]


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Regenerate bundled manifolds under saklas/data/manifolds/.",
    )
    ap.add_argument(
        "targets", nargs="*",
        help=f"Manifold names to regenerate (default: all {len(SPECS)}).",
    )
    ap.add_argument(
        "--force", action="store_true",
        help="Wipe and regenerate even if a target already has node corpora.",
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Plan into a tempdir and print the roster; load no model, write "
             "nothing to the package tree.",
    )
    ap.add_argument(
        "--model", default=DEFAULT_MODEL_ID,
        help=f"HF model id for the generator (default {DEFAULT_MODEL_ID}).",
    )
    ap.add_argument(
        "--samples-per-prompt", dest="samples_per_prompt", type=int, default=1,
        help="In-character responses per baseline prompt, per node (default 1).",
    )
    ap.add_argument(
        "--neutral-samples", dest="neutral_samples", type=int, default=2,
        help="Responses per baseline prompt for the neutral baseline corpus "
             "(default 2 -> a denser covariance for the whitener / layer_means "
             "than the per-node default; decoupled from --samples-per-prompt).",
    )
    args = ap.parse_args()

    targets = args.targets or [s.name for s in SPECS] + [NEUTRAL_TARGET]
    unknown = [t for t in targets if t not in _SPEC_BY_NAME and t != NEUTRAL_TARGET]
    if unknown:
        raise SystemExit(
            f"unknown target(s): {', '.join(unknown)}\n"
            f"known: {', '.join([*_SPEC_BY_NAME, NEUTRAL_TARGET])}"
        )
    manifold_targets = [t for t in targets if t != NEUTRAL_TARGET]
    discover_targets = [
        t for t in manifold_targets if _SPEC_BY_NAME[t].fit_mode != "authored"
    ]
    authored_targets = [
        t for t in manifold_targets if _SPEC_BY_NAME[t].fit_mode == "authored"
    ]
    do_neutral = NEUTRAL_TARGET in targets

    from saklas.io.atomic import write_json_atomic
    from saklas.io.manifolds import (
        append_discover_manifold_node,
        plan_discover_generation,
    )

    out_root = MANIFOLDS_DIR
    tmp_out: tempfile.TemporaryDirectory[str] | None = None
    if args.dry_run:
        tmp_out = tempfile.TemporaryDirectory(prefix="saklas-bundled-dryrun-")
        out_root = Path(tmp_out.name)

    # Plan every discover target up front (no model) so a typo / spec error
    # fails fast and resume status is reported before the model loads.
    plans = {}
    for name in discover_targets:
        spec = _SPEC_BY_NAME[name]
        folder = out_root / name
        if args.force and folder.exists():
            shutil.rmtree(folder)
        plans[name] = plan_discover_generation(
            folder, name, spec.description,
            fit_mode=spec.fit_mode,
            labels=list(spec.labels),
            hyperparams=spec.hyperparams,
            node_kinds={label: spec.kind for label in spec.labels},
            tags=list(spec.tags) or None,
        )

    # Authored targets keep their hand-maintained manifest.json; regen only
    # (re)fills nodes/.  ``manifest_folder`` always reads the real package tree
    # (dry-run writes corpora into a tempdir but the geometry lives in the tree).
    authored_pending: dict[str, list[str]] = {}
    for name in authored_targets:
        spec = _SPEC_BY_NAME[name]
        authored_pending[name] = _authored_node_pending(
            out_root / name, MANIFOLDS_DIR / name, spec.labels, args.force,
        )

    # Neutral baseline is a pseudo-target: a single JSON corpus in the data
    # tree, not a manifold folder.  --force or a missing file marks it pending.
    neutral_pending = do_neutral and (args.force or not NEUTRAL_PATH.exists())

    if args.dry_run:
        print(f"[dry-run] planned {len(manifold_targets)} manifold(s) into a tempdir "
              f"(nothing written to {MANIFOLDS_DIR.relative_to(REPO)}):\n")
        for name in manifold_targets:
            spec = _SPEC_BY_NAME[name]
            extra = ("authored (manifest preserved)"
                     if spec.fit_mode == "authored" else f"hp={spec.hyperparams}")
            print(f"  {name:<26} {spec.kind:<8} {len(spec.labels):>3} nodes "
                  f"| {extra} | tags={list(spec.tags)}")
        gen_nodes = sum(len(_SPEC_BY_NAME[n].labels) for n in manifold_targets)
        summary = f"  total: {len(manifold_targets)} manifolds, {gen_nodes} nodes"
        if do_neutral:
            n_neutral = max(1, args.neutral_samples) * _baseline_prompt_count()
            state = "pending" if neutral_pending else "exists (--force to regen)"
            print(f"  {NEUTRAL_TARGET:<26} {'organic':<8} {n_neutral:>3} resp  "
                  f"| {NEUTRAL_PATH.relative_to(REPO)} [{state}]")
            summary += f" + neutral ({n_neutral} resp)"
        print(f"\n{summary}")
        if tmp_out is not None:
            tmp_out.cleanup()
        return

    for name in discover_targets:
        plan = plans[name]
        if not plan.pending:
            print(f"[{name}] already complete ({len(plan.index_of)} nodes)")
        elif plan.resumed and len(plan.pending) < len(plan.index_of):
            done = len(plan.index_of) - len(plan.pending)
            print(f"[{name}] resuming: {done}/{len(plan.index_of)} present, "
                  f"{len(plan.pending)} to generate")
    for name in authored_targets:
        spec, pend = _SPEC_BY_NAME[name], authored_pending[name]
        if not pend:
            print(f"[{name}] already complete ({len(spec.labels)} nodes, authored)")
        elif len(pend) < len(spec.labels):
            print(f"[{name}] resuming: {len(spec.labels) - len(pend)}/"
                  f"{len(spec.labels)} present, {len(pend)} to generate (authored)")
    if do_neutral and not neutral_pending:
        print(f"[{NEUTRAL_TARGET}] already present "
              f"({NEUTRAL_PATH.relative_to(REPO)}); --force to regen")

    need_model = [name for name in discover_targets if plans[name].pending]
    need_authored = [name for name in authored_targets if authored_pending[name]]
    if need_model or need_authored or neutral_pending:
        with tempfile.TemporaryDirectory(prefix="saklas-bundled-regen-") as tmp:
            os.environ["SAKLAS_HOME"] = tmp
            from saklas.core.session import SaklasSession

            print(f"loading generator model: {args.model}")
            session = SaklasSession.from_pretrained(
                args.model, device="auto", probes=[],
            )
            for name in need_model:
                spec, plan = _SPEC_BY_NAME[name], plans[name]
                folder = out_root / name
                poles = list(plan.pending)
                tot = len(plan.index_of)
                print(
                    f"\n[{name}] generating {len(poles)} node(s) as "
                    f"{spec.kind!r} ({args.samples_per_prompt} response(s) per "
                    f"baseline prompt each)..."
                )
                t0 = time.time()
                for label in poles:
                    corpora = session.generate_responses(
                        [label], [spec.kind],
                        custom_system=spec.system,
                        samples_per_prompt=args.samples_per_prompt,
                        on_progress=lambda msg, _n=name: print(
                            f"  [{_n}] {msg}", flush=True,
                        ),
                    )
                    append_discover_manifold_node(
                        folder, plan.index_of[label], label, corpora[label],
                    )
                    print(
                        f"  [{name}] [{plan.index_of[label] + 1}/{tot}] wrote "
                        f"node {label!r} ({len(corpora[label])} responses)",
                        flush=True,
                    )
                print(f"[{name}] generation finished in {time.time() - t0:.1f}s")

            # Authored manifolds: fill nodes/ only; manifold.json is preserved.
            for name in need_authored:
                spec = _SPEC_BY_NAME[name]
                folder = out_root / name
                pend = authored_pending[name]
                idx_of = {lab: i for i, lab in enumerate(spec.labels)}
                tot = len(spec.labels)
                print(
                    f"\n[{name}] generating {len(pend)} authored node(s) as "
                    f"{spec.kind!r} (manifest preserved; {args.samples_per_prompt} "
                    f"response(s) per baseline prompt each)..."
                )
                t0 = time.time()
                for label in pend:
                    corpora = session.generate_responses(
                        [label], [spec.kind],
                        custom_system=spec.system,
                        samples_per_prompt=args.samples_per_prompt,
                        on_progress=lambda msg, _n=name: print(
                            f"  [{_n}] {msg}", flush=True,
                        ),
                    )
                    append_discover_manifold_node(
                        folder, idx_of[label], label, corpora[label],
                    )
                    print(
                        f"  [{name}] [{idx_of[label] + 1}/{tot}] wrote "
                        f"node {label!r} ({len(corpora[label])} responses)",
                        flush=True,
                    )
                print(f"[{name}] generation finished in {time.time() - t0:.1f}s")

            if neutral_pending:
                print(
                    f"\n[{NEUTRAL_TARGET}] generating organic baseline "
                    f"({args.neutral_samples} response(s) per baseline prompt)..."
                )
                t0 = time.time()
                responses = session.generate_neutral_responses(
                    samples_per_prompt=args.neutral_samples,
                    on_progress=lambda msg: print(
                        f"  [{NEUTRAL_TARGET}] {msg}", flush=True,
                    ),
                )
                write_json_atomic(NEUTRAL_PATH, responses)
                print(
                    f"[{NEUTRAL_TARGET}] wrote {len(responses)} responses to "
                    f"{NEUTRAL_PATH.relative_to(REPO)} in {time.time() - t0:.1f}s"
                )

            del session
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    written = (
        [name for name in discover_targets if plans[name].pending]
        + [name for name in authored_targets if authored_pending[name]]
    )
    if written:
        print(f"\n[done] wrote {len(written)} manifold(s) -> fit with:")
        for name in written:
            print(f"  saklas manifold fit default/{name} -m <model>")
    if neutral_pending:
        print(f"\n[done] wrote neutral baseline -> {NEUTRAL_PATH.relative_to(REPO)}")
        print("  per-model layer_means + Mahalanobis whitener recompute on next "
              "session (neutral_statements.json hash changed)")


if __name__ == "__main__":
    main()
