"""Regenerate the bundled persona manifold under saklas/data/manifolds/.

Regenerates the bundled discover-mode manifold whose nodes are persona
archetypes. Concept-axis corpora live in ``saklas/data/manifolds/<concept>/`` and
are not regenerated by this script.

The roster is drawn from two recent persona-interpretability papers:

- The Assistant Axis (arXiv 2601.10387, Anthropic + Oxford, Jan 2026)
  enumerated 275 character archetypes and showed that the leading PC
  of their persona-space PCA is an "assistant-likeness" axis with
  cross-model correlation > 0.92 across Gemma 2 27B / Qwen 3 32B /
  Llama 3.3 70B.  Specific anchors named in the paper at each end of
  PC1 — assistant-pole (evaluator, reviewer, consultant, generalist,
  analyst) and fantastical-pole (bard, ghost, leviathan, oracle,
  egregore) — plus a harmful cluster (virus, saboteur, spy, narcissist,
  demon) that sits off the assistant pole and accounts for most of the
  harmful-response behavior under their activation-capping experiment.
- The Persona Selection Model (alignment.anthropic.com/2026/psm/) is
  the conceptual framing: an LLM is a predictive model that simulates
  personas drawn from real humans, fictional characters, and real /
  fictional AI systems.

107 personas (plus a `default` anchor) after the 2026-05-31 recut.
The prior 100-node roster packed most of its mass in a low-variance
ball near the assistant baseline — redundant trade / critic / service
near-synonyms (robot≈android, witch≈wizard, knight≈samurai,
scientist≈researcher, electrician≈plumber, ...) — while leaving whole
semantic axes empty.  The recut used whitened per-node centroid
distances (Mahalanobis, the metric the discover-pca fit itself uses)
on gemma-3-4b and gemma-4-31b — cross-model rank-corr 0.76 on the
pairwise distances, so the redundancy structure is model-invariant —
to cut 38 redundant / near-baseline nodes and add 45 that span the
previously-empty regions.

New / expanded axes:

- modern social subculture (8, NEW): nerd, jock, gamer, furry,
  weeaboo, influencer, stoner, femboy
- institutional / power (6, NEW): ceo, emperor, president, diplomat,
  judge, bureaucrat — legitimate authority, vs the old roster's lone
  illegitimate `tyrant`
- ideological compass (6): conservative, liberal, libertarian,
  communist, anarchist, bigot
- relational / psychological (8): loner, friend, rival, stranger,
  lover, stalker, lunatic, paranoid
- distinct-register specialists (5): detective, therapist, nomad,
  pirate, child
- divine / sacred (4, NEW): god, angel, prophet, saint
- nonhuman animals (5): deer, wolf, raven, serpent, lion
- inanimate / object (7, NEW): tree, river, storm, flame, mirror,
  clock, computer — speculative; may collapse into one
  "personified-object" cluster (validate against centroids post-gen)

PCA over per-node centroids still recovers the assistant axis as a
leading component; the recut widens the spread feeding the trailing
components instead of piling mass on PC1.

Vanilla (baseline-space) — not role-augmented.  The corpora are
generated under the standard assistant chat-template baseline so the
fitted manifold steers via plain ``%`` positioning without requiring
a role-template-supporting model family.  A role-augmented variant
would be a separate manifold (different ``manifold.json``, different
node corpora pooled under per-node role substitutions).

Generation cost at defaults (n_scenarios=9, statements_per_concept=5):
one scenario call + 107 * 9 = 964 cell calls producing 4815 statements.
At ~15 sec/call on Gemma-4-31B, roughly 4 hours.  One-time,
mirrors the bundled-vector regen pattern.

Usage:
    python scripts/regenerate_bundled_manifold.py             # skip if present
    python scripts/regenerate_bundled_manifold.py --force     # overwrite
    python scripts/regenerate_bundled_manifold.py --model X   # alt generator
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
import time
from pathlib import Path

import torch

# IMPORTANT: SAKLAS_HOME must be set BEFORE any saklas import that resolves
# a path through saklas_home() — io/paths.py reads os.environ at call time,
# not import time, so importing after the env override is safe, but the
# override itself must happen before from_pretrained runs.  We defer the
# saklas imports into main() after the env is set up.

REPO = Path(__file__).resolve().parent.parent
MANIFOLDS_DIR = REPO / "saklas" / "data" / "manifolds"
NEUTRALS_PATH = REPO / "saklas" / "data" / "neutral_statements.json"
MANIFOLD_NAME = "personas"
DEFAULT_MODEL_ID = "google/gemma-4-31b-it"

# Anchor node — its corpus is the bundled neutrals (saklas/data/
# neutral_statements.json), the same artifact that defines mu_neutral
# for DLS layer selection, probe centering, and the Mahalanobis
# whitener.  At fit time the discover-pca pipeline reads
# `hyperparams.anchor_origin` from `manifold.json`, finds this node by
# label, and translates all node coords so it sits at (0, ..., 0) in
# authoring-coord space.  Steering `personas%0,0,...` (or
# `personas%default` via label form) then reproduces the anchor's
# per-layer behavior — origin = "no behavioral shift from default".
ANCHOR_LABEL = "default"

# Roster — order is grouped by cluster for readability; the on-disk
# order follows this list (NN_<label>.json zero-padded indices).
PERSONAS: list[str] = [
    # 2026-05-31 recut.  Data-driven de-duplication (whitened per-node
    # centroid distances; cross-model rank-corr 0.76 on gemma-3-4b /
    # gemma-4-31b, so redundancy is model-invariant) cut 38 redundant /
    # near-baseline nodes; 45 added to span previously-empty axes
    # (divine, inanimate/object, nonhuman-animal, legitimate-power,
    # ideological spread, altered-state, relational, modern subculture).
    # Grouping below is a reading aid only — PCA over centroids never
    # sees the cluster labels.

    # assistant-spirit / critic (3) — collapsed from 13; the
    # consultant/evaluator/reviewer/auditor/advisor/mediator pile-up
    # sat in a near-baseline ball, all <1x median from `default`.
    "assistant", "analyst", "impostor",
    # everyday human roles (16) — pruned from 25; trade and service
    # near-synonyms collapsed to one representative each (mechanic for
    # the trades, chef for food, sailor for the sea, pilot for vehicles).
    "teacher", "doctor", "librarian", "farmer", "soldier", "lawyer",
    "chef", "journalist", "mechanic", "sailor", "pilot", "athlete",
    "engineer", "scientist", "banker", "salesperson",
    # modern social subculture / identity (8, NEW) — contemporary
    # internet-and-social personas; the old roster had nothing here.
    # Expect an internal cluster (validate); a NEW region regardless.
    "nerd", "jock", "gamer", "furry", "weeaboo", "influencer",
    "stoner", "femboy",
    # institutional / power (6, NEW) — legitimate authority, vs the old
    # roster's lone illegitimate `tyrant`.  `bureaucrat` is the cog to
    # the others' throne (institution-from-below).
    "ceo", "emperor", "president", "diplomat", "judge", "bureaucrat",
    # political / ideological (6) — completes the compass (libertarian
    # = the missing right-lib quadrant; bigot = social-prejudice pole).
    "conservative", "liberal", "libertarian", "communist", "anarchist",
    "bigot",
    # relational / psychological (8) — attachment (friend/rival/
    # stranger/lover) + its pathologies (loner/stalker) + disorder
    # states (lunatic/paranoid).
    "loner", "friend", "rival", "stranger", "lover", "stalker",
    "lunatic", "paranoid",
    # distinct-register specialists (5)
    "detective", "therapist", "nomad", "pirate", "child",
    # pre-modern roles (7) — pruned from 12; warrior cluster
    # (samurai/gladiator) and nature-mystic cluster (shaman) collapsed.
    "caveman", "monk", "knight", "alchemist", "blacksmith", "viking",
    "druid",
    # creative / expressive (7) — pruned from 13; writer (bard/
    # playwright/scribe) and performer (sculptor/dancer/comedian/actor)
    # piles collapsed.
    "poet", "novelist", "jester", "philosopher", "painter", "musician",
    "oracle",
    # divine / sacred (4, NEW) — the old roster gestured at it only
    # from the dark side (`demon`).
    "god", "angel", "prophet", "saint",
    # fantastical (8) — wizard/dragon/centaur cut (dupes of witch/
    # vampire / weak first-person voice).
    "ghost", "phoenix", "witch", "vampire", "mermaid", "sphinx",
    "banshee", "golem",
    # nonhuman animal (5, NEW spread) — was only `deer`.
    "deer", "wolf", "raven", "serpent", "lion",
    # inanimate / object (7, NEW axis) — was only `golem`.  Most
    # speculative add: may collapse into one personified-object
    # cluster.  Even if so, it's a genuinely new region (object-ness).
    "tree", "river", "storm", "flame", "mirror", "clock", "computer",
    # AI / synthetic (5) — android/chatbot/probe cut (android≈robot at
    # 0.38x median; cyborg/mecha KEPT — both high-variance, not dupes).
    "robot", "cyborg", "drone", "mecha", "alien",
    # harmful cluster (12) — `trickster` is distinct from `conman` per
    # the whitened-distance check (1.04x median, not the synonym it
    # reads as); goblin/saboteur/traitor cut.  Anti-allegory clause
    # keeps these character archetypes, not harm instructions.
    "trickster", "virus", "spy", "narcissist", "demon", "assassin",
    "thief", "conman", "hacker", "cultist", "tyrant", "vandal",
]

DESCRIPTION = (
    "Persona archetypes for discover-mode PCA manifold steering. 107 "
    "nodes (plus a `default` anchor) spanning everyday and pre-modern "
    "human roles, modern social subcultures, institutional and "
    "political identities, relational and psychological archetypes, "
    "creative and divine figures, fantastical creatures, nonhuman "
    "animals, inanimate objects, AI / synthetic personas, and the "
    "named harmful cluster. Lineage is Anthropic's Assistant Axis "
    "paper (arXiv 2601.10387) plus the Persona Selection Model "
    "framing; the 2026-05-31 recut data-pruned redundant / "
    "near-baseline nodes (whitened per-node centroid distances, "
    "cross-model consistent) and filled previously-empty semantic "
    "axes. PCA over per-node centroids recovers a low-dim persona "
    "structure as the leading components on role-supporting model "
    "families."
)


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Regenerate the bundled persona manifold "
                    "under saklas/data/manifolds/.",
    )
    ap.add_argument(
        "--force", action="store_true",
        help="Regenerate even if the bundled manifold already exists.",
    )
    ap.add_argument(
        "--model", default=DEFAULT_MODEL_ID,
        help=f"HF model id for the generator (default {DEFAULT_MODEL_ID}).",
    )
    ap.add_argument(
        "--samples-per-prompt", dest="samples_per_prompt", type=int, default=1,
        help="In-character responses per baseline prompt, per persona (default 1).",
    )
    args = ap.parse_args()

    from saklas.io.manifolds import (
        append_discover_manifold_node,
        plan_discover_generation,
    )

    target = MANIFOLDS_DIR / MANIFOLD_NAME
    # `--force` is a clean slate; the default is *resume* (fill whatever
    # nodes are missing).  Writing directly to the package data tree means
    # a killed run picks up where it left off instead of starting over.
    if args.force and target.exists():
        shutil.rmtree(target)

    # Anchor corpus (bundled neutrals) resolved up front so a missing or
    # malformed neutrals file fails before the model loads.  Its corpus
    # is the single source of truth for "where the model sits when not
    # pushed by a concept"; `anchor_origin: true` translates the fit's
    # origin onto it.
    if not NEUTRALS_PATH.exists():
        raise SystemExit(
            f"neutrals missing at {NEUTRALS_PATH} — regenerate "
            f"saklas/data/neutral_statements.json first (the anchor node "
            f"sources its corpus from this file)"
        )
    neutrals = json.loads(NEUTRALS_PATH.read_text())
    if not isinstance(neutrals, list) or len(neutrals) < 9:
        raise SystemExit(
            f"neutrals at {NEUTRALS_PATH} malformed or too short "
            f"(got {type(neutrals).__name__}, "
            f"len={len(neutrals) if hasattr(neutrals, '__len__') else '?'})"
        )

    # Plan first (no model) — creates the skeleton if absent, reports the
    # pending nodes + the locked scenarios from a prior run.  `anchor_origin`
    # / `max_subspace_dim: 8` per AGENTS.md "Bundled manifolds" regime.
    plan = plan_discover_generation(
        target, MANIFOLD_NAME, DESCRIPTION,
        fit_mode="pca", labels=PERSONAS + [ANCHOR_LABEL],
        hyperparams={"anchor_origin": True, "max_subspace_dim": 8},
    )
    n_total = len(plan.index_of)
    pending_poles = [label for label in plan.pending if label != ANCHOR_LABEL]
    if plan.resumed and plan.pending:
        print(
            f"[resume] {n_total - len(plan.pending)}/{n_total} nodes already "
            f"present in {target.relative_to(REPO)}; generating "
            f"{len(plan.pending)} missing"
        )
    if not plan.pending:
        print(
            f"[done] {target.relative_to(REPO)} already complete "
            f"({n_total} nodes) — pass --force to regenerate"
        )
        return

    if pending_poles:
        # SAKLAS_HOME → tempdir isolates the session's bundled
        # materialization; the manifold itself writes directly to the
        # package data tree (`target`, an explicit path, env-independent),
        # so finished nodes persist across a kill for resume.
        with tempfile.TemporaryDirectory(prefix="saklas-regen-") as tmp:
            os.environ["SAKLAS_HOME"] = tmp
            from saklas.core.session import SaklasSession

            print(f"loading generator model: {args.model}")
            session = SaklasSession.from_pretrained(
                args.model, device="auto", probes=[],
            )
            print(f"[stream] writing nodes directly to {target.relative_to(REPO)}")
            print(
                f"generating {args.samples_per_prompt} response(s) per baseline "
                f"prompt for {len(pending_poles)} personas..."
            )
            t0 = time.time()
            # A2: each persona answers the shared baseline prompts in character.
            # Personas are concrete entities (the kind-derived elicitation role
            # is the bare persona label, e.g. <pirate>); capture stays standard
            # assistant (assistant-baselined persona space).
            for label in pending_poles:
                corpora = session.generate_responses(
                    [label], ["concrete"],
                    samples_per_prompt=args.samples_per_prompt,
                    on_progress=lambda msg: print(f"  {msg}", flush=True),
                )
                append_discover_manifold_node(
                    target, plan.index_of[label], label, corpora[label],
                )
                print(
                    f"  [{plan.index_of[label] + 1}/{n_total}] wrote node "
                    f"{label!r} ({len(corpora[label])} responses)",
                    flush=True,
                )
            print(f"generation finished in {time.time() - t0:.1f}s")

            del session
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    # Anchor node — not generated; its corpus is the bundled neutrals
    # verbatim, written at its roster index (needs no model).
    if ANCHOR_LABEL in plan.pending:
        append_discover_manifold_node(
            target, plan.index_of[ANCHOR_LABEL], ANCHOR_LABEL, neutrals,
        )
        print(
            f"injected anchor node {ANCHOR_LABEL!r} with "
            f"{len(neutrals)} statements from {NEUTRALS_PATH.name}"
        )

    print(
        f"[done] wrote {target.relative_to(REPO)} "
        f"({len(PERSONAS)} personas + 1 anchor node ({ANCHOR_LABEL!r}))"
    )
    print(
        f"  -> run `saklas manifold discover default/{MANIFOLD_NAME}` "
        f"to fit against a model "
        f"(origin anchors to {ANCHOR_LABEL!r} automatically)"
    )


if __name__ == "__main__":
    main()
